# Generated by Django 5.0.4 on 2024-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_about_descriptions2_alter_about_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
    ]
