# Generated by Django 5.0.4 on 2024-05-07 14:23

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_settings_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image1',
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок слайда'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_image/', verbose_name='Фотография для первого слайда')),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_image/', verbose_name='Фотография для второго слайда')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_doing', to='base.slide')),
            ],
            options={
                'verbose_name_plural': 'Фотографии для слайда',
            },
        ),
    ]
