# Generated by Django 5.0.4 on 2024-05-07 14:32

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_slide_options_remove_slide_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_image/', verbose_name='Фотография для первого слайда')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_doing1', to='base.slide')),
            ],
            options={
                'verbose_name_plural': 'Фотографии  для первого столбца',
            },
        ),
        migrations.CreateModel(
            name='SlideImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_image/', verbose_name='Фотография для первого слайда')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_doing2', to='base.slide')),
            ],
            options={
                'verbose_name_plural': 'Фотографии для второго столбца',
            },
        ),
        migrations.DeleteModel(
            name='SlideImage',
        ),
    ]
