# Generated by Django 4.2 on 2023-04-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_setting_app_alter_setting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='graphic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы'),
        ),
    ]
