# Generated by Django 4.2 on 2023-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_setting_graphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Первое описание')),
                ('desscriptions2', models.TextField(verbose_name='Второе описание')),
                ('image', models.ImageField(upload_to='about_image', verbose_name='Фотография')),
                ('experience', models.CharField(max_length=255, verbose_name='опыт')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
