# Generated by Django 4.2 on 2023-04-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
