# Generated by Django 4.2 on 2023-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_remove_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=255, verbose_name='Год')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши истории',
                'verbose_name_plural': 'Наша история',
            },
        ),
    ]
