# Generated by Django 4.2 on 2023-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(default=1, upload_to='history_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
