# Generated by Django 4.2 on 2023-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_history_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=255, verbose_name='Активные клиенты')),
                ('review', models.CharField(max_length=255, verbose_name='Положительных отзывов')),
                ('team', models.CharField(max_length=255, verbose_name='Юристов')),
            ],
            options={
                'verbose_name': 'Мы в числах',
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
