# Generated by Django 4.2 on 2023-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='graphic_clock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы в часах'),
        ),
    ]
