# Generated by Django 4.2 on 2023-04-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Наши юристы', 'verbose_name_plural': 'Наш юрист'},
        ),
    ]
