# Generated by Django 4.2 on 2023-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='youtube',
            new_name='telegram',
        ),
    ]
