# Generated by Django 4.2 on 2023-05-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_youtube_team_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='telegram',
        ),
    ]
