# Generated by Django 4.2 on 2023-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo_site')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('locate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('graphic', models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы')),
                ('graphic_clock', models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы в часах')),
                ('locate_url', models.URLField(blank=True, null=True, verbose_name='Ссылка для адресса')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram для показа')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('app', models.URLField(blank=True, null=True, verbose_name='Ссылка для приложения')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
