# Generated by Django 4.2 on 2023-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='instagram_url',
        ),
    ]
