# Generated by Django 4.2 on 2023-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_setting_instagram_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='locate_url',
        ),
    ]
